services:
  # ==========================================
  # CAPA DE BASES DE DATOS (Infraestructura)
  # ==========================================
  postgres-db:
    image: postgres:15-alpine
    container_name: arena_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:6.0
    container_name: arena_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis-db:
    image: redis:7-alpine
    container_name: arena_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  # ==========================================
  # CAPA DE MICROSERVICIOS (Rust Backend)
  # ==========================================
  auth-service:
    build: 
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: arena_auth
    restart: always
    environment:
      # ¡IMPORTANTE! En Docker, ya no usamos 'localhost', usamos el nombre del contenedor
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis-db:6379
    depends_on:
      - postgres-db
      - redis-db

  game-engine:
    build: 
      context: .
      dockerfile: services/game-engine/Dockerfile
    container_name: arena_game
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017
      REDIS_URL: redis://redis-db:6379
    depends_on:
      - postgres-db
      - mongo-db
      - redis-db

  api-gateway:
    build: 
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: arena_gateway
    restart: always
    ports:
      - "8080:8080" # ¡ESTE ES EL ÚNICO PUERTO QUE EXPONEMOS AL FRONTEND!
    depends_on:
      - auth-service
      - game-engine

volumes:
  postgres_data:
  mongo_data:
  redis_data: