# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayStream = channel.stream_stream(
                '/arena.game.GameService/PlayStream',
                request_serializer=game__pb2.ClientMessage.SerializeToString,
                response_deserializer=game__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.SendEmoji = channel.unary_unary(
                '/arena.game.GameService/SendEmoji',
                request_serializer=game__pb2.EmojiRequest.SerializeToString,
                response_deserializer=game__pb2.EmojiAck.FromString,
                _registered_method=True)
        self.LaunchQuestion = channel.unary_unary(
                '/arena.game.GameService/LaunchQuestion',
                request_serializer=game__pb2.QuestionPayload.SerializeToString,
                response_deserializer=game__pb2.ModeratorAck.FromString,
                _registered_method=True)
        self.ForceEndTimer = channel.unary_unary(
                '/arena.game.GameService/ForceEndTimer',
                request_serializer=game__pb2.ForceEndRequest.SerializeToString,
                response_deserializer=game__pb2.ModeratorAck.FromString,
                _registered_method=True)
        self.ApprovePlayer = channel.unary_unary(
                '/arena.game.GameService/ApprovePlayer',
                request_serializer=game__pb2.ApprovePlayerRequest.SerializeToString,
                response_deserializer=game__pb2.ModeratorAck.FromString,
                _registered_method=True)
        self.DenyPlayer = channel.unary_unary(
                '/arena.game.GameService/DenyPlayer',
                request_serializer=game__pb2.DenyPlayerRequest.SerializeToString,
                response_deserializer=game__pb2.ModeratorAck.FromString,
                _registered_method=True)
        self.StartGame = channel.unary_unary(
                '/arena.game.GameService/StartGame',
                request_serializer=game__pb2.StartGameRequest.SerializeToString,
                response_deserializer=game__pb2.ModeratorAck.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmoji(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LaunchQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceEndTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApprovePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenyPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PlayStream,
                    request_deserializer=game__pb2.ClientMessage.FromString,
                    response_serializer=game__pb2.ServerMessage.SerializeToString,
            ),
            'SendEmoji': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmoji,
                    request_deserializer=game__pb2.EmojiRequest.FromString,
                    response_serializer=game__pb2.EmojiAck.SerializeToString,
            ),
            'LaunchQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchQuestion,
                    request_deserializer=game__pb2.QuestionPayload.FromString,
                    response_serializer=game__pb2.ModeratorAck.SerializeToString,
            ),
            'ForceEndTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceEndTimer,
                    request_deserializer=game__pb2.ForceEndRequest.FromString,
                    response_serializer=game__pb2.ModeratorAck.SerializeToString,
            ),
            'ApprovePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.ApprovePlayer,
                    request_deserializer=game__pb2.ApprovePlayerRequest.FromString,
                    response_serializer=game__pb2.ModeratorAck.SerializeToString,
            ),
            'DenyPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.DenyPlayer,
                    request_deserializer=game__pb2.DenyPlayerRequest.FromString,
                    response_serializer=game__pb2.ModeratorAck.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=game__pb2.StartGameRequest.FromString,
                    response_serializer=game__pb2.ModeratorAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arena.game.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arena.game.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arena.game.GameService/PlayStream',
            game__pb2.ClientMessage.SerializeToString,
            game__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEmoji(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/SendEmoji',
            game__pb2.EmojiRequest.SerializeToString,
            game__pb2.EmojiAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LaunchQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/LaunchQuestion',
            game__pb2.QuestionPayload.SerializeToString,
            game__pb2.ModeratorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceEndTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/ForceEndTimer',
            game__pb2.ForceEndRequest.SerializeToString,
            game__pb2.ModeratorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApprovePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/ApprovePlayer',
            game__pb2.ApprovePlayerRequest.SerializeToString,
            game__pb2.ModeratorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenyPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/DenyPlayer',
            game__pb2.DenyPlayerRequest.SerializeToString,
            game__pb2.ModeratorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.game.GameService/StartGame',
            game__pb2.StartGameRequest.SerializeToString,
            game__pb2.ModeratorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
